#+TITLE: Org2blog, la herramienta de emacs para bloguear
#+DATE: 19:41, 2011-09-14
#+SETUPFILE: ~/.emacs.d/setupfile.org
#+JEKYLL_AUTHOR: Pablo Alvarez de Sotomayor Posadillo
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: [emacs, org2blog, org-mode]
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true
#+AUTHOR: Pablo Álvarez de Sotomayor Posadillo
#+EMAIL: palvarez@ritho.net

¡Buenas a todos desde Brasil!

Hace algunos días descubrí una herramienta que me puede ayudar a
bloguear con bastante más frecuencia, Org2Blog. Es básicamente un
plugin del paquete org para publicar posts desde ficheros org con
emacs. No he usado anteriormente org-mode, asi que he estado
investigando un poco y he podido comprobar que no es sólo un paquete
para publicar entradas en el blog, sino que además es una herramienta
para administrar tu agenda y tu lista de cosas poor hacer, así que he
estado unos días configurándolo y me da la impresión de que lo voy a
usar bastante y me va a ser de gran ayuda.

La parte de blog parece ser bastante sencilla, porque puedes definir
el post con unas cuantas etiquetas sencillas de recordar y no define
ningún formato extraño para escribir el post (como hacen muchos
wikis). Tu sólo te tienes que ocupar de escribir el post en texto
*plano* y el paquete se las arregla para convertirlo en tu entrada html.

Aunque creo que se puede usar para otros blogs distintos de Wordpress,
te recomiendo que mires que paquete funciona mejor para tu blog (por
ejemplo, para blogger hay un paquete que parece funcionar mejor que
este) antes de intentar volverte loco configurando este.

Una de las cosas que quiero probar en los próximos días es la
integración con Atom, ya que esa integración se hace con otro paquete
y hasta ahora no he conseguido hacerlo funcionar.

Espero poder bloguear mucho mas con esta herramienta, porque una de
las cosas que odio de los blogs es tener que estar conectado y con un
navegador abierto para escribir una entrada.

Happy Hacking!
