#+TITLE: #SpanishRevolution, part II
#+DATE: 02:10, 2011-09-14
#+SETUPFILE: ~/.emacs.d/setupfile.org
#+JEKYLL_AUTHOR: Pablo Alvarez de Sotomayor Posadillo
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: General
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true
#+AUTHOR: Pablo Álvarez de Sotomayor Posadillo
#+EMAIL: palvarez@ritho.net

In the [[https://blogs.fsfe.org/palvarez/2011/08/19/spanishrevolution-part-i/][first part]] of this post I've explained the economical situation
of Spain and how we've reached this situation. Now it's the turn to
explain a little bit the origins of the Indignados movement ant the
recent history of the social movements in Spain.

The Indignados movement (or #15M) born officially the 15 of May of
2011, although I think the real begining started before. In order to
understand better the origins of the #15M it's better to explain a
little bit the recent phistory of the social movements in Spain.

As you might know, before the actual democracy Spain was headed by
Francisco Franco, a dictator aligned ideologically with Hitler. Some
years before his dead (1975) the social movements in Spain begans to
be very strong, and, although they had to be subversive (the
government was very represive even after the dead of Franco), they
gain a lot of popularity, specially in the young people.

After 1975 and during the 80's Spain became into a cultural and
political revolution, and a lot of political parties (included PSOE
and the Comunist Party) and labor unions (CCOO, UGT, CNT, ...) were
legalized. This was the golden epoch of the social movements in Spain,
because a lot of people were conscious that it was important to be
part of the (not only) political change that was happening in Spain
and, a very important thing, they were a part of this changes, in part
because the government were taking them into consideration and making
changes in the way the social movements were saying.

After that, during the final 80s and the 90s the political parties
forgot about the people and began to govern for themselves and for the
"markets" (a.k.a the rich people) and the social movements began to
accommodate, partially because the social situation were much better
than during the dictatorial period and partially because some state
mechanisms made the social movements too dependents from the
government charity, and in the moment that any organization depends
on the government it has to do some things and leave to do other
things to please them and survive.

I think that the reaction to this circumstances come both from a new
social movement surged in Spain (and in the world :)), the Free
Software movement, that has become very strong sice the final 90s, and
from the deterioration of the spanish life style, specially with the
actual crisis environment.

In the last years we've seen here in Spain a lot of movement against
the software patents in Europe and agains some copyright laws that
have emerged in the last years in Spain, and a big part of this
movement has been lead by hacktivist that have been participated in
the Free Software movement during several years.

This movements have been organized dinamically, without a need of a
phisical organization, and in several times during a specific period
of time. This has made that the state, with his old mechanisms of
working, couldn't stop this kind of organization, that have made the
enough noise to influence again in the political life of the country
and in the spanish people.

This was the kind of organization of #nolesvotes, the father of
the #15m (or indignados) movement, who asks to vote in the municipal
elections to any party but PSOE or PP, rised after the approval of an
unfair copyright law by the two main political parties of
Spain. Because of that #nolesvotes gained the support and/or
comprehension of the population, being, in my point of view, a big
success.

To be continued...
