#+TITLE: Org2blog, the emacs blogging experience
#+DATE: 19:41, 2011-09-14
#+SETUPFILE: ~/.emacs.d/setupfile.org
#+JEKYLL_AUTHOR: Pablo Alvarez de Sotomayor Posadillo
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: emacs, org2blog, org-mode
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true
#+AUTHOR: Pablo Álvarez de Sotomayor Posadillo
#+EMAIL: palvarez@ritho.net

Hi from Brasil!

Some days ago I've discovered a tool that can help me to blog more
frequently, Org2Blog. It's basically a plugin for the org package to
publish posts from org files in emacs. I didn't used previously
org-mode, so I've investigated a bit about it and I found that I can
use it not only for blog posting, but also to manage your agenda and
todo list, so I've configured it out and I think I'm going to use it a
lot.

The blogging part seems to be pretty easy, because you can define your
post entry with a few and easy to remember tags and it doesn't define
any weird format to write (like a lot of wiki pages). You only have to
write your post in *plain* text and the package manage to convert it
to your html entry.

Although I think you can use it not only for Wordpress, I recomend you
to search for other packages if you're using other blog engine (for
example, there is a package that works better with blogger that seems to work
better than this one).

One of the thinks that I want to try in the next few days is the
integration of org2blog with atom. This integration is made by other
package and I couldn't do it work in the last days.

I hope to blog much more with this tool, cause one of the things that
I hate of blogging is the necessity of being connected and with a
browser opened to post an entry.

Happy Hacking!
