#+TITLE: #SpanishRevolution, part III
#+DATE: 00:22, 2011-10-10
#+SETUPFILE: ~/.emacs.d/setupfile.org
#+JEKYLL_AUTHOR: Pablo Alvarez de Sotomayor Posadillo
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: General
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true
#+AUTHOR: Pablo Álvarez de Sotomayor Posadillo
#+EMAIL: palvarez@ritho.net

In the [[https://blogs.fsfe.org/palvarez/2011/09/14/spanishrevolution-part-ii/][second part]] of this post I've explained the recent history and
evolution of the social movements in Spain. In this post I'm going to
focus in #15m (or Indignados) movement, how they've started, their
proposals, things that, *IMHO*, they've done well, things to improve
and where they should go.

As I said in my previous post, Indignados movement has been influenced
by the #nolesvotes movement, which shows both how to self-organize in
a global way (the opposite of the traditional social movements has
done historically, working at a neighborhood level or, at best, at a
city level) and how the new technologies can help in this
self-organization, but, obviously, it's not the only movement that has
influenced to #15M.

In recent years the social movements in Spain have seen a revival in
grassroots organization, whose work in the neighborhoods has been an
essential breeding ground for movement #15M. These grassroots
organizations have a participatory democracy based on people's
assemblies and consensus decision making. These horizontally
structured assemblies are completely transparent and open to anyone
who wants to participate. The groundwork has served not only to learn
work techniques and methodologies assemblies, but also enabled them to
know the people, know their concerns and problems and know how to work
with them.

Therefore, having these two movements as parents it's not strange how
quickly this movement has emerged and spread throughout all the country,
in a way that only a few people could imagine.

On January 2011, the digital platform Democracia real YA (one of the
main actors in #15M movement) was created on Spanish social networks
and forums. Having the support of organisations such as ATTAC,
Intermon Oxfam, Ecologists in Action or Youth without Future, and
using Twitter and Facebook it called "the unemployed, poorly paid, the
subcontractors, the precarious, young people..." to take the streets
on 15 May in almost every city in Spain (you have at Wikipedia a
comprehensive list of all the places that were called to take the
streets on that day). That same day, small demonstrations in support
of the Spanish ones were organised in Dublin, Lisbon, Amsterdam,
Istanbul, Bologna, London and Paris.

The first protest was called under the motto "we are not goods in the
hands of politicians and bankers" and was focused on opposition to
what the protesters called "antisocial means in the hands of bankers",
partly referring to the changes made in 2010 to contain the ongoing
European sovereign debt crisis through bailout of the banks, which the
Spanish society saw as responsible for the crisis, while at the same
time the government kept announcing social program cutbacks.
Protesters also demanded more democracy, a new electoral law and end
to political corruption as well as other claims, such as banks
nationalisation.

The main demand of #15M is a radical change in Spanish politics, and,
although #15M is a heterogeneous and ambiguous group, they share a
strong rejection of unemployment, welfare cuts, Spanish politicians,
the current two-party system in Spain between the Spanish Socialist
Workers' Party and the People's Party, as well as the current
political system, capitalism, banks and bankers, political corruption
and firmly support what they call basic rights: home, work, culture,
health and education.

As #nolesvotes, they don't consider themselves to be represented by
any traditional party nor favoured by the measures approved by
politicians. If you want to know more about the #15M proposals and
actions you can visit their [[http://movimiento15m.org/][official page]] and read their [[http://movimiento15m.org/manifiesto-movimiento-15m-%c2%a1democracia-real-ya/#more-5][manifesto]].

The impact of #15M has been bigger than anyone thought, because
according to statistics published by RTVE (the Spanish public
broadcasting company) between 6.5 and 8 million Spaniards have
participated in these protests, an unthinkable thing at the beginning
of the year, and in this kind of things you can't trust the official
information, so probably the participation has been even more.

I think the most important thing that this movement has made is to
make the spanish population aware that we can change the actual
situation of our country, because a lot of people didn't think they
can do something to make a change.

Also, I think that #15M can have a life much longer than much people
can imagine, from one side because the changes they are proposing are
big ones, and they need time to define both the changes we have to
make to have a fairly society and the strategy to make this changes
possible, and from the other side because they have reach a big impact
in the population, a lot of people has been a part of #15M, and being
part of a movement like this makes you feel that your contribution is
important, and, although sometimes you can desperate, this is a
feeling that once you have it you want to keep it.

Seeing the movement from the outside (although I wanted to involve
myself in the movement I couldn't find the time until now) I think
that sometimes they've enter in the politician's game more than they
needs, but, obviously, it's a new and complex situation to handle and
it can't be perfect.

The movement has passed some critical times and situations (like the
time after the local elections or the Pope visit), and they'll going
to pass some more critical situations, but I think that the most
important one is to handle the people's mood (it's a long path and a
lot of people can desperate).

Finally, although the movement can end in nothing, I think that the
process is very important, not only because we're trying to change
important thinks, but also because we are changing the point of view
of a lot of people that, until now, they didn't realize they can make
a change, and this is the seed of future revolutions.

Happy Hacking!

P.D.: You can access to information about the 15-M movement at the
wikipedia [[https://secure.wikimedia.org/wikipedia/es/wiki/Movimiento_15-M][here]], [[https://secure.wikimedia.org/wikipedia/es/wiki/15M][here]] (in spanish) and [[https://secure.wikimedia.org/wikipedia/en/wiki/2011_Spanish_protests][here]] (in english).

P.P.D.: All the ideas I expose here are personal opinions, comming
only from myself, and here I don't represent any of the organizations
I belong to.

