#+TITLE: Latest adquisitionsn
#+DATE: 23:09, 2012-03-03
#+SETUPFILE: ~/.emacs.d/setupfile.org
#+JEKYLL_AUTHOR: Pablo Alvarez de Sotomayor Posadillo
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: General
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true
#+AUTHOR: Pablo Álvarez de Sotomayor Posadillo
#+EMAIL: palvarez@ritho.net

Hi all!

I'm back from South America (I've been 6 weeks in Chile and Argentina)
with some good and bad news. The bad new is that I've been stolen and
I don't have anymore some of my technical stuff, like a laptop, an
external hard drive, a tablet and some other things. I've also lost
some information, specially documentation and some projects of my
studies and previous works.

The good thing is that I've to restore some of the things I've lost,
so I bought a desktop computer and a netbook. The desktop computer is
an AMD with 8 cores of 3.1GHz each, 8 GB of RAM, a 1 GB graphic card
with hdmi output and a 120 GB SSD hard drive. Yes, it's a great
computer, so it's going to stay with me for a really long time.

The other toy I've bought, the netbook, is an Asus eeepc of 10' with
two cores of 1.67GHz each, 1 GB of RAM and a hard drive of 250 GB,
more than enough to have mobility and a real computer for my
travels. I think that between the two toys I'm going to be very
productive, so I hope you'll see me more active in my projects and
around here.

Happy Hacking!!!
